config/routes.rb
Rails.application.routes.draw do
  get 'residences/index'
  resources :residences
  resources :auctions
  resources :reservations 
  get 'reservation/hotsale', to: 'reservations#create_hotsale'
  resources :hotsales
  resources :bids
  get '/auction/winner', to:'auctions#winner'
  get '/contacto', to: 'contacts#show'
  get '/terminosycondiciones', to: 'conditions#show'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
      }
  get '/users/index', to: 'users#index'
  get '/users/make_premium', to: 'users#make_premium'


  root 'residences#index'
end

app/models/auction.rb
class Auction < ApplicationRecord
	belongs_to :residence
	has_many :bids, dependent: :destroy
	validates :residence_id, :uniqueness => {:scope => [:in_date]}
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index 
  	@auctions= Auction.all
  end

  def default
  end
  
  def new
    r=Residence.find(params[:residence])
    residence_id=r.id
  	@auction= Auction.new(residence_id: residence_id)
  end

  def show
  	@auction= Auction.find(params[:id])
  end

  def update
    @auction = Auction.find(params[:id])
    @a = Auction.new(params.require(:auction).permit(:in_date))
    if @a.in_date.wday == 1
        if (@a.in_date.month - Time.now.month) + 12 * (@a.in_date.year - Time.now.year) >= 6
          if @auction.update(params.require(:auction).permit(:amount,:in_date,:bid))
            flash.notice = "La subasta #{@auction.residence.name} ha sido actualizada"
            redirect_to auctions_path
          else
            render :edit
          end
        else
          flash.now[:alert] = 'Se debe crear con 6 meses de anticipacion'
          render :edit
        end     
    else
      flash.now[:alert] = 'La subasta debe comenzar un lunes'
      render :edit
    end
  end

  def destroy
  	auction= Auction.find(params[:id])
  	if auction.destroy
      flash.notice = "La subasta '#{auction.residence.name}' ha sido eliminada"
  		redirect_to auctions_path
  	else
      flash.alert = "ERROR al eliminar la subasta '#{auction.residence.name}'"
  		redirect_to auctions_path 
  	end
  end

  def edit
    @auction=Auction.find(params[:id])
  end

  def create
    @auction= Auction.new(params.require(:auction).permit(:amount,:in_date,:bid,:residence_id))
    if !(Hotsale.where({in_date: @auction.in_date, residence_id: @auction.residence_id}).any?)
      if !(Reservation.where({in_date: @auction.in_date, residence_id: @auction.residence_id}).any?)
        if @auction.in_date.wday == 1 
            if (@auction.in_date.month - Time.now.month) + 12 * (@auction.in_date.year - Time.now.year) >= 6
              if @auction.save 
                flash.notice = "La subasta se creo exitosamente"
                redirect_to auctions_path
              else  
                flash.now[:alert] = 'Ya existe la subasta'
                redirect_to auctions_path
              end
            else
              flash.now[:alert] = 'Se debe crear con 6 meses de anticipacion'
              render :new
            end     
        else
          flash.now[:alert] = 'La subasta debe comenzar un lunes'
          render :new
        end
      else
        flash.now[:alert] = 'La residencia se encuentra reservada para esa fecha'
        render :new
      end
    else 
        flash.now[:alert] = 'La residencia se encuentra en hot sale para esa fecha'
        render :new
    end  
  end

  def winner
    @encontro=false
    @auction=Auction.find(params[:id])
    @auction.bids.order(amount: :desc).each do |b|
      if @auction.amount < b.amount
        if User.find(b.user_id).reservations.count < 2
          r=Reservation.new(in_date:b.auction.in_date,residence_id:b.auction.residence_id,user_id:b.user_id)
          if r.save
            flash.notice = "El ganador es #{User.find(b.user_id).name}, se le asigno una reserva"
            @encontro=true
            redirect_to auctions_path
            break
          end
        end
      end
    end
    if !@encontro
      flash.alert = "No hay ganador"
      redirect_to auctions_path
    end
  end

end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<div class="container">
<%= form_for @auction do |auction| %>
	<div class="form-group">
	  <div class="row">
	  	<div class="col-4">
	  	    <h3><%= auction.label :name, @auction.residence.name%></h3>
	  	    <%= auction.hidden_field :residence_id%>
	  	</div>
	  </div>
      <div class="row">
	    <div class="col-4">
          <%= auction.label :amount, 'Monto minimo' %>
    	  <%= auction.text_field :amount, class: 'form-control', placeholder: "Ingrese el monto minimo", required: true %>
        </div>
      </div>
      <div class="row">
      	<div class="col-4">
      		<%= auction.label :in_date, 'Fecha de inicio de la semana' %>
      		<%= auction.date_field :in_date, class: 'form-control', required: true %>
        </div>
      </div>
	</div>
	<%= auction.submit 'guardar', class: 'btn btn-success' %>
	<%= link_to 'volver', residences_path, class: 'btn btn-link' %>
<%end%>
</div>

app/views/auctions/edit.html.erb
<h1><%= @auction.residence.name %></h1>
<%= render 'form' %>

app/views/auctions/index.html.erb
<h3>Subastas</h3>
<table class="table">
	<thead>
		<tr>
			<th width="10%">Nombre</th>
			<th width="10%">Puja</th>
			<th width="20%">Foto</th>
			<th width="15%">Fecha de reserva</th>
			<th width="15%">Fecha inicio</th>
			<th width="5%">Ganador</th>
			<th width="5%"></th>
			<th width="5%"></th>
			<th width="5%"></th>
		</tr>
	</thead>
	<tbody>
		<% @auctions.each do |auction| %>
			<tr>
				<%@cumple=true%>
				<%if !(auction.in_date-6.month<=Time.now and auction.in_date-6.month+4.days>Time.now) %>
				  <%@cumple=false%>
				<%end%> 
				<% current_user.reservations.each do |r| %>
					<% if r.in_date == auction.in_date %>
					<% @cumple=false %>
					<%end%>
				<%end%>
				<% if @cumple %>
					<td><%= link_to auction.residence.name, new_bid_path(:auction => auction.id, :user => current_user.id) %></td>
				<%else%>
					<td><%=auction.residence.name%></td>
				<%end%>
				<% if auction.bids.count > 0 %>
					<td>$<%= auction.bids.order(amount: :desc).first.amount %></td>
				<%else%>
					<td>$0</td>
				<%end%>
				<td><img src="<%= auction.residence.photo%>" width="300"></td>
				<td><%= auction.in_date.strftime("%d-%m-%Y") %></td>
				<td><%= (auction.in_date-6.month).strftime("%d-%m-%Y") %></td>
				<% if auction.residence.reservations.where(in_date: auction.in_date).any? %>
					<td><%=User.find(auction.residence.reservations.where(in_date: auction.in_date).first.user_id).name%></td>
				<%else%>
					<td>-------</td>
				<%end%> 
				<% if current_user.admin %>
					<% if auction.in_date-6.month+4.days<=Time.now and !(auction.residence.reservations.where(in_date: auction.in_date).any?) %>
						<td><%= link_to 'Determinar ganador', auction_winner_path(:id => auction.id), class: 'btn btn-primary', data: { confirm: '¿realmente desea determinar el ganador' } %></td>
					<%else%>
						<td><button type="button" class="btn btn-primary" disabled>Determinar ganador</button></td>
					<%end%>
					<td><%= link_to 'Editar', edit_auction_path(auction), class: 'btn btn-warning' %></td>
					<td><%= link_to 'Eliminar', auction, method: :delete, class: 'btn btn-danger', data: { confirm: '¿realmente desea eliminar la subasta?' } %></td>
				<%end%>
			</tr>
		<% end %>
	</tbody>
</table>
</br>

app/views/auctions/new.html.erb
<h3>Nueva subasta</h3>
<%= render 'form' %>