config/routes.rb
Rails.application.routes.draw do
  get 'residences/index'
  resources :residences
  resources :auctions
  resources :reservations 
  get 'reservation/hotsale', to: 'reservations#create_hotsale'
  resources :hotsales
  resources :bids
  get '/auction/winner', to:'auctions#winner'
  get '/contacto', to: 'contacts#show'
  get '/terminosycondiciones', to: 'conditions#show'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
      }
  get '/users/index', to: 'users#index'
  get '/users/make_premium', to: 'users#make_premium'


  root 'residences#index'
end

app/models/residence.rb
class Residence < ApplicationRecord
	has_many :auctions, dependent: :destroy
	has_many :reservations, dependent: :destroy
	has_many :hotsales, dependent: :destroy
	validates :name, :uniqueness => {:scope => [:country, :address, :capacity, :photo,]}

	def is_available?(start_date,end_date,num)
		if reservations.where(:in_date => start_date..end_date).count < num
			reservations.where(:in_date => start_date..end_date)
		else
        	reservations.where(:in_date => start_date..end_date).empty?
        end
    end
end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
  def new
    @residence= Residence.new
  end

  def show
    @residence=Residence.find(params[:id])
  end

  def index 
    if params[:date1].present? && params[:date2].present?
      if "%#{params[:date1]}%".to_date > Date.today+6.months
        if "%#{params[:date2]}%".to_date >= "%#{params[:date1]}%".to_date+7.days && "%#{params[:date2]}%".to_date <= "%#{params[:date1]}%".to_date+2.months 
          search1 = "%#{params[:text]}%" 
          search2 = "%#{params[:date1]}%"
          search3 = "%#{params[:date2]}%"
          num = (("%#{params[:date2]}%".to_date - "%#{params[:date1]}%".to_date).to_i+1)/7
          @residences = Residence.where('name LIKE ? OR country LIKE ?',search1,search1).select {|res| res.is_available?(search2,search3,num)}
        else
          flash.alert = "La diferencia entre fechas debe ser como maximo de 2 meses y como minimo de 1 semana"
          redirect_to residences_path
        end
      else
        flash.alert = "La fecha tiene que ser dentro de 6 meses"
        redirect_to residences_path
      end
    else
      @residences= Residence.all
    end
  end

  def default
  end

  def update
    @residence=Residence.find(params[:id])

      if @residence.update(params.require(:residence).permit(:name,:country,:address,:capacity,:photo))
        redirect_to residences_path
      else
        flash.now[:alert] = 'La residencia ya existe'
        render :edit
      end
  end

  def destroy
    residence=Residence.find(params[:id])

    if residence.destroy
      flash.notice = "La Residencia '#{residence.name}' ha sido eliminada"
      redirect_to residences_path
    else
      flash.alert = "Error al eliminar la Residencia '#{residence.name}'"
      redirect_to residences_path
    end
  end

  def edit
    @residence=Residence.find(params[:id])
  end

  def create
    @residence=Residence.new(params.require(:residence).permit(:name,:country,:address,:capacity,:photo))

      if @residence.save
        redirect_to residences_path
      else
        flash.now[:alert] = 'La residencia ya existe'
        render :new
      end
    
  end
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/_form.html.erb
<div class="container">

	<%= form_for @residence do |r| %>
		<div class="row">
			<div class="col-md-4">
				<%= r.label :name, 'Nombre' %>
				<%= r.text_field :name, class: 'form-control', label: 'Nombre',maxlength: 20 , placeholder: 'Ingrese el nombre',required: true %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<%= r.label :country, 'Pais' %>
				<%= r.text_field :country, class: 'form-control', label: 'Pais',maxlength: 15 , placeholder: 'Ingrese el pais',required: true %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<%= r.label :address, 'Direccion' %>
				<%= r.text_field :address, class: 'form-control', label: 'direccion',maxlength: 20 , placeholder: 'Ingrese la direccion',required: true %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<%= r.label :capacity, 'Capacidad' %>
				<%= r.number_field :capacity, class: 'form-control', label: 'Capacidad',in: 1.0..10.0 ,step: 1, placeholder: 'Ingrese la capacidad',required: true %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<%= r.label :photo, 'Foto' %>
				<%= r.text_field :photo, class: 'form-control', label: 'Foto', placeholder: 'Ingrese la imagen',required: true %>
			</div>
		</div>
		<%= r.submit "Guardar Residencia", class: 'btn btn-primary' %>
		<%= link_to 'Volver', residences_path, class: 'btn btn-default'%>
	<%end%>
	
</div>

app/views/residences/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1><%= @residence.name %></h1>
<%= render 'form' %>

app/views/residences/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HomeSwitchHome</title>
</head>
<body>
  
<h1>Lista de Residencias</h1>
  <div class="container">
  <div class="row">
    <% @residences.each do |residence| %>
      <div class="col-4">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="<%= residence.photo%>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= link_to residence.name, residence %></h5>
            <% if signed_in? %>
               <% if current_user.admin %>
                   <p><%= link_to "Agregar subasta", new_auction_path(:residence => residence.id), class: 'btn btn-warning btn-sm' %></p>
                   <p><%= link_to "Agregar hot-sale", new_hotsale_path(:residence => residence.id), class: 'btn btn-warning btn-sm' %></p>
                   <a><%= link_to "Editar", edit_residence_path(residence), class: 'btn btn-info btn-sm' %>
                       <%= link_to "Eliminar",residence, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: '¿Realmente queres eliminar la residencia?'} %>
                   </a>
               <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  </div>
  <% if signed_in? %>
     <% if current_user.admin %>
      <div class="row">
        <div class="col-12" style="text-align: center;">
          <%= link_to 'Nueva Residencia', new_residence_path, class: 'btn btn-primary', :align => :center %>
        </div>
      </div>
    <% end %>
  <% end %>
</body>
</html>

app/views/residences/new.html.erb
<h1>Crear una nueva residencia</h1>
<%= render 'form' %>

app/views/residences/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HomeSwitchHome</title>
</head>
<body>
  <div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="<%= @residence.photo %>" alt="<%= @residence.name %>" title="<%= @residence.name %>" width="500" />
        </div>
        <div class="col-md-6">
            <blockquote>
                <p><%= @residence.name %></p> <small><cite title="Source Title"><%= @residence.address %>, <%= @residence.country %>  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
            </blockquote>
            <p> Capacidad: <%= @residence.capacity %></p>
            <% if signed_in? %>
                <% if current_user.premium %>
                    <%= link_to 'Reservar', new_reservation_path(:residence => @residence.id), class: 'btn btn-primary'%>
                <%end%>
            <%end%>
        </div>
    </div>
    <%= link_to 'Volver', residences_path, class: 'btn btn-primary'%>
</div>

</body>
</html>