config/routes.rb
Rails.application.routes.draw do
  get 'residences/index'
  resources :residences
  resources :auctions
  resources :reservations 
  get 'reservation/hotsale', to: 'reservations#create_hotsale'
  resources :hotsales
  resources :bids
  get '/auction/winner', to:'auctions#winner'
  get '/contacto', to: 'contacts#show'
  get '/terminosycondiciones', to: 'conditions#show'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
      }
  get '/users/index', to: 'users#index'
  get '/users/make_premium', to: 'users#make_premium'


  root 'residences#index'
end

app/models/hotsale.rb
class Hotsale < ApplicationRecord
	belongs_to :residence
	validates :residence_id, :uniqueness => {:scope => [:in_date]}
end

app/controllers/hotsales_controller.rb
class HotsalesController < ApplicationController
	def index
		@hotsales= Hotsale.all
	end

	def new
		r=Residence.find(params[:residence])
    	residence_id=r.id
  		@hotsale= Hotsale.new(residence_id: residence_id)
	end

	def show
		@hotsale= Hotsale.find(params[:id])
	end

	def update
		@hotsale = Hotsale.find(params[:id])
    	@h = Hotsale.new(params.require(:hotsale).permit(:in_date))
    	if @h.in_date.wday == 1
    		if @h.in_date > Time.now
        		if @hotsale.update(params.require(:hotsale).permit(:amount,:in_date))
            		flash.notice = "El hot-sale #{@hotsale.residence.name} ha sido actualizado"
            		redirect_to hotsales_path
        		else
            		render :edit
            	end
            else 
            	flash.now[:alert] = 'El hot-sale debe comenzar como mínimo mañana'
        		render :edit
        	end    
    	else
        	flash.now[:alert] = 'El hot-sale debe comenzar un lunes'
        	render :edit
    	end
	end

	def create
		@hotsale= Hotsale.new(params.require(:hotsale).permit(:amount,:in_date,:residence_id))
        if !(Auction.where({in_date: @hotsale.in_date, residence_id: @hotsale.residence_id}).any?)
          if !(Reservation.where({in_date: @hotsale.in_date, residence_id: @hotsale.residence_id}).any?)
            if @hotsale.in_date.wday == 1 
                if @hotsale.in_date > Time.now
        		  if @hotsale.save 
            		flash.notice = "El hot-sale se creo exitosamente"
            		redirect_to hotsales_path
        		  else  
            		flash.now[:alert] = 'Ya existe el hot-sale'
            		redirect_to hotsales_path
        		  end
        	    else
        		  flash.now[:alert] = 'El hot-sale debe comenzar como mínimo mañana'
        		  render :new  
        	    end
    	    else
    		flash.now[:alert] = 'El hot-sale debe comenzar un lunes'
        	render :new
    	    end
          else
            flash.now[:alert] = 'La residencia se encuentra reservada para esa fecha'
            render :new
          end
        else
            flash.now[:alert] = 'La residencia se encuentra en subasta para esa fecha'
            render :new
        end
	end

	def edit
		@hotsale=Hotsale.find(params[:id])
	end

	def destroy
  		hotsale= Hotsale.find(params[:id])
  		if hotsale.destroy
    	  flash.notice = "El hot-sale '#{hotsale.residence.name}' ha sido eliminado"
  		  redirect_to hotsales_path
  		else
    	  	flash.alert = "ERROR al eliminar el hot-sale '#{hotsale.residence.name}'"
  			redirect_to hotsales_path 
  		end
	end
end

app/helpers/hotsale_helper.rb
module HotsaleHelper
end

app/views/hotsales/_form.html.erb
<div class="container">
<%= form_for @hotsale do |hotsale| %>
	<div class="form-group">
	  <div class="row">
	  	<div class="col-4">
	  	    <h3><%= hotsale.label :name, @hotsale.residence.name%></h3>
	  	    <%= hotsale.hidden_field :residence_id%>
	  	</div>
	  </div>
      <div class="row">
	    <div class="col-4">
          <%= hotsale.label :amount, 'Costo' %>
    	  <%= hotsale.text_field :amount, class: 'form-control', placeholder: "Ingrese el monto", required: true %>
        </div>
      </div>
      <div class="row">
      	<div class="col-4">
      		<%= hotsale.label :in_date, 'Fecha de inicio de la semana' %>
      		<%= hotsale.date_field :in_date, class: 'form-control', required: true %>
        </div>
      </div>
	</div>
	<%= hotsale.submit 'guardar', class: 'btn btn-success' %>
	<%= link_to 'volver', residences_path, class: 'btn btn-link' %>
<%end%>
</div>

app/views/hotsales/edit.html.erb
<h1><%= @hotsale.residence.name %></h1>
<%= render 'form' %>

app/views/hotsales/index.html.erb
<h3>Hot-sales</h3>
<table class="table">
	<thead>
		<tr>
			<th width="10%">Nombre</th>
			<th width="10%">Valor</th>
			<th width="50%">Foto</th>
			<th width="10%">Fecha</th>
			<th width="10%"></th>
			<th width="10%"></th>
			<th colspan="6"></th>
		</tr>
	</thead>
	<tbody>
		<% @hotsales.each do |hotsale| %>
			<tr>
				<td><%= link_to hotsale.residence.name, hotsale_path(hotsale) %></td>
				<td>$<%= hotsale.amount %></td>
				<td><img src="<%= hotsale.residence.photo%>" width="300"></td>
				<td><%= hotsale.in_date.strftime("%d-%m-%Y") %></td>
				<% if current_user.admin %>
					<td><%= link_to 'Editar', edit_hotsale_path(hotsale), class: 'btn btn-warning' %></td>
					<td><%= link_to 'Eliminar', hotsale, method: :delete, class: 'btn btn-danger', data: { confirm: '¿realmente desea eliminar el Hot-Sale?' } %></td>
				<%end%>
			</tr>
		<% end %>
	</tbody>
</table>
</br>

app/views/hotsales/new.html.erb
<h3>Nuevo Hot-Sale</h3>
<%= render 'form' %>

app/views/hotsales/show.html.erb
<html>
<head>
	<title>HomeSwitchHome</title>
</head>
<body>
  <div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="img-responsive" src="<%= @hotsale.residence.photo %>" alt="<%= @hotsale.residence.name %>" title="<%= @hotsale.residence.name %>" width="500" />
        </div>
        <div class="col-md-6">
            <blockquote>
                <p><%= @hotsale.residence.name %></p> <small><cite title="Source Title"><%= @hotsale.residence.address %>, <%= @hotsale.residence.country %>  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
            </blockquote>
            <p> Capacidad: <%= @hotsale.residence.capacity %></p>
            <p> Fecha: <%= @hotsale.in_date.strftime("%d-%m-%Y") %></p>
            <p> Valor: $<%= @hotsale.amount %> </p>
            <% if signed_in? %>
                <% if !(Reservation.where({residence_id: @hotsale.residence.id, in_date: @hotsale.in_date}).any?) %>
                    <%= link_to 'Reservar', reservation_hotsale_path(:in_date => @hotsale.in_date,:user_id => current_user.id, :residence_id => @hotsale.residence.id, :hotsale_id => @hotsale.id), class: 'btn btn-primary'%>
                <%end%>
            <%end%>
        </div>
    </div>
    <%= link_to 'Volver', hotsales_path, class: 'btn btn-primary'%>
</div>

</body>
</html>