config/routes.rb
Rails.application.routes.draw do
  get 'residences/index'
  resources :residences
  resources :auctions
  resources :reservations 
  get 'reservation/hotsale', to: 'reservations#create_hotsale'
  resources :hotsales
  resources :bids
  get '/auction/winner', to:'auctions#winner'
  get '/contacto', to: 'contacts#show'
  get '/terminosycondiciones', to: 'conditions#show'

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
      }
  get '/users/index', to: 'users#index'
  get '/users/make_premium', to: 'users#make_premium'


  root 'residences#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
	belongs_to :residence
	has_many :bids, dependent: :destroy
	validates :residence_id, :uniqueness => {:scope => [:in_date]}
end

app/models/bid.rb
class Bid < ApplicationRecord
	belongs_to :user
	belongs_to :auction
end

app/models/hotsale.rb
class Hotsale < ApplicationRecord
	belongs_to :residence
	validates :residence_id, :uniqueness => {:scope => [:in_date]}
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :residence
	belongs_to :user
	validates :residence_id, :uniqueness => {:scope => [:in_date]}
	validates :user_id, :uniqueness => {:scope => [:in_date]}
end

app/models/residence.rb
class Residence < ApplicationRecord
	has_many :auctions, dependent: :destroy
	has_many :reservations, dependent: :destroy
	has_many :hotsales, dependent: :destroy
	validates :name, :uniqueness => {:scope => [:country, :address, :capacity, :photo,]}

	def is_available?(start_date,end_date,num)
		if reservations.where(:in_date => start_date..end_date).count < num
			reservations.where(:in_date => start_date..end_date)
		else
        	reservations.where(:in_date => start_date..end_date).empty?
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservations, dependent: :destroy
  has_many :bids, dependent: :destroy
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

	def new
		user_id=params[:user]
		auction_id=params[:auction]
		@bid=Bid.new(user_id: user_id, auction_id: auction_id)
	end

	def create
		@bid=Bid.new(params.require(:bid).permit(:amount, :user_id, :auction_id))
		if @bid.auction.bids.present?
		if @bid.auction.bids.order(amount: :desc).first.user_id != @bid.user_id
			if @bid.save
				flash.notice = "La puja se registro exitosamente"
				redirect_to auctions_path
			else
				flash.alert = "ERROR al registrar la puja"
				render :new
			end
		else
			flash.alert = "Usted posee la puja mas alta"
			render :new
		end
		else
			if @bid.save
				flash.notice = "La puja se registro exitosamente"
				redirect_to auctions_path
			else
				flash.alert = "ERROR al registrar la puja"
				render :new
			end
		end
	end
end

app/controllers/prueva_controller.rb
class PruevaController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def make_premium
  	@user=User.find(params[:id])
    if @user.premium
      @user.premium=false
    else
  	  @user.premium=true
    end
  	if @user.save
  		flash.notice = "El usuario ya es premium"
  		redirect_to users_index_path
  	else
  		flash.alarm = "ERROR al hacer usuario premium"
  		redirect_to users_index_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hotsale_helper.rb
module HotsaleHelper
end

app/helpers/prueva_helper.rb
module PruevaHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb

<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag "HSH-Logo.svg", class: "rounded float-left", width: 50, height: 50 %>
  <%end%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Inicio', '/residences', class: "nav-link" %>
      </li>
      <% if current_user %>
      <li class="nav-item">
          <%= link_to 'Subastas', '/auctions', class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to 'Hot-Sales', '/hotsales', class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Contacto', '/contacto', class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Terminos y condiciones', '/terminosycondiciones', class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= form_tag residences_path, method: :get, enforce_utf8: false  do %>
      <%= text_field_tag :text, nil, class: "form-control mr-sm-1", placeholder: "Ingrese Nombre" %>
      <%= date_field_tag :date1, nil, class: "form-control mr-sm-1",required: true %>
      <%= date_field_tag :date2, nil, class: "form-control mr-sm-1",required: true %>
      <%= submit_tag "Buscar", name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </form>
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <%= current_user.name %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><%= link_to 'Editar' , edit_user_registration_path, class: "nav-link"%></a>
            <a class="dropdown-item" href=""><%= link_to 'Mis reservaciones', reservations_path(:id => current_user.id), class: "nav-link" %></a>
            <% if current_user.admin %>
            <a class="dropdown-item" href="#"><%= link_to 'Lista de usuarios', users_index_path, class: "nav-link" %></a>
            <%end%>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><%= link_to 'Cerrar sesion', destroy_user_session_path,method: :delete, class: "nav-link" %></a>
          </div>
        </li>
      </ul>
    <% else %>
    <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Iniciar sesion', new_user_session_path, class: "nav-link" %>
        </li>
        </ul>
    <% end %>
  </div>
</nav> 
  <% if notice%>
    <div class="alert alert-success" role="alert"><%= notice %></div>
  <%end%>
  <% if alert%>
  <div class="alert alert-danger" role="alert"><%= alert %></div>
  <%end%>

 
</header>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeSwitchHome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'HSH-Logo.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" data-turbolinks-track='false'>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" data-turbolinks-track='false'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous" data-turbolinks-track='false'></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous" data-turbolinks-track='false'></script>
  </body>
  <base></base>
</html>